name: k8 Deployment

on:
  push:
    branches: ['main']


env:
  PROJECT_ID: ${{secrets.GKE_ID}}
  GKE_CLUSTER: cc-final-cluster
  GKE_ZONE: us-central1-c
  DEPLOYMENT_NAME: cc-deployment-edit
  IMAGE: github-actions-gke-image-edit
  TAG: 1.0.0

jobs:
  GKE_CICD: 
    name: CICD Pipeline in GKE 
    runs-on: ubuntu-latest
    steps:
      - name: Check the Repo 
        uses: actions/checkout@v3
        
      - name: Setup CLI in GCP
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          service_account_key: ${{secrets.GKE_SA}}
          project_id: ${{secrets.GKE_ID}}

      - name: Docker Configuration
        run: |-
          gcloud --quiet auth configure-docker

      - name: Credential Validation - GKE
        run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
      
      - name: Build the docker Image
        run: |-
          docker build --tag "gcr.io/$PROJECT_ID/$IMAGE:$TAG" .
      
      - name: Push docker image to GCR
        run: |-
          docker push "gcr.io/$PROJECT_ID/$IMAGE:$TAG"
      
      - name: Set up Kustomize file
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize
          
      - name: Final Deployment - GKE
        run: |-
          gcloud components install gke-gcloud-auth-plugin
          ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE:TAG=gcr.io/$PROJECT_ID/$IMAGE:$TAG
          ./kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/$DEPLOYMENT_NAME
          kubectl get services -o wide
